default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: 5819Lincoln@
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_back_end_development

test:
  <<: *default
  database: hello_rails_back_end_test

production:
  <<: *default
  database: hello_rails_back_end_production
  username: postgres
  password: <%= ENV["HELLO_RAILS_BACK_END_DATABASE_PASSWORD"] %>
